### ISSUE TITLE
Make `BlockEnv` configurable

### ISSUE THREAD

**Issue by onbjerg** [risechain/block-stm-revm#15]
Some opcodes rely on information in `BlockEnv`, e.g. `COINBASE`, `NUMBER`, `BLOCKHASH`.

Ref https://docs.rs/revm/latest/revm/interpreter/primitives/struct.BlockEnv.html

**Comment by hai-rise** [comment]
Quickly addressed in #20.

Feel free to re-open if you need more; our API is still very messy & experimental 🙏.
